In [5]:
import numpy as np

### Normalization Problem


In [11]:
#Create a 5x5 array with random values
X = np.random.random((5,5))

#Get mean of X
mean = X.mean()

#Get standard deviation of X 
std = X.std()

#Normalize X
result = Z = X-mean/std

#Print normalized array
print(Z)

#Save the result as 'X_normalized'
np.save('X_normalized', result)

[[-0.7310814  -1.44145137 -1.14992181 -1.24987028 -0.5707779 ]
 [-0.9462251  -1.4752446  -0.79512296 -1.29136809 -1.39735777]
 [-1.01161692 -1.39058528 -0.89562514 -0.59630747 -1.34609976]
 [-1.03521332 -1.4243251  -0.89841974 -0.58345742 -0.67022209]
 [-1.45949778 -0.76406951 -1.10618023 -0.70457559 -1.33221546]]


### Divisible by 3 Problem

In [13]:
#Create an array of positive integers from 1 to 100
positive_integers = np.arange(1,101)

#Create another array but of squares of positive integers from 1 to 100 by raising the first array to 2
A = positive_integers**2

#Reshape array A into 10 x 10 
shape = A.reshape(10,10)

#Define a function so that elements divisible by 3 may be determined; true for divisible elements and false for otherwise
result = elements_divisible_by_3 = shape%3==0 

#Print result
print(elements_divisible_by_3)

#Save the result as 'div_by_3.npy'
np.save('div_by_3.npy', result)

[[False False  True False False  True False False  True False]
 [False  True False False  True False False  True False False]
 [ True False False  True False False  True False False  True]
 [False False  True False False  True False False  True False]
 [False  True False False  True False False  True False False]
 [ True False False  True False False  True False False  True]
 [False False  True False False  True False False  True False]
 [False  True False False  True False False  True False False]
 [ True False False  True False False  True False False  True]
 [False False  True False False  True False False  True False]]
