In [5]:
import numpy as np

### Normalization Problem


In [55]:
#Create a 5x5 array with random values
X = np.random.random((5,5))

#Get mean of X
mean = X.mean()

#Get standard deviation of X 
std = X.std()

#Normalize X
result = Z = X-mean/std

#Print normalized array
print(" X array: \n", X)
print("\n Z array (X Normalized): \n", result)

#Save the result as 'X_normalized'
np.save('X_normalized', result)

 X array: 
 [[0.23020064 0.21892663 0.76874111 0.75454106 0.58891901]
 [0.40531309 0.31865683 0.5441868  0.84373332 0.51016502]
 [0.03410143 0.30263887 0.6964076  0.14376412 0.78962065]
 [0.91534378 0.51787898 0.98764456 0.22125134 0.2698113 ]
 [0.24409239 0.93063702 0.49026228 0.2461465  0.91937279]]

 Z array (X Normalized): 
 [[-1.5973309  -1.6086049  -1.05879043 -1.07299047 -1.23861252]
 [-1.42221844 -1.50887471 -1.28334473 -0.98379821 -1.31736651]
 [-1.7934301  -1.52489266 -1.13112393 -1.68376742 -1.03791088]
 [-0.91218775 -1.30965256 -0.83988697 -1.6062802  -1.55772023]
 [-1.58343914 -0.89689452 -1.33726926 -1.58138503 -0.90815875]]


### Divisible by 3 Problem

In [43]:
#Create an array of positive integers from 1 to 100
positive_integers = np.arange(1,101)

#Create another array but of squares of positive integers from 1 to 100 by raising the first array to 2
A = positive_integers**2

#Reshape array A into 10 x 10 
shape = A.reshape(10,10)

#Define a function so that elements divisible by 3 may be determined; true for divisible elements and false for otherwise
result = elements_divisible_by_3 = shape[shape%3==0] 

#Print result

print("Squares of the first 100 positive integers: \n", A) 
print("\nElements divisible by 3: \n", result)

#Save the result as 'div_by_3.npy'
np.save('div_by_3.npy', result)

Squares of the first 100 positive integers: 
 [    1     4     9    16    25    36    49    64    81   100   121   144
   169   196   225   256   289   324   361   400   441   484   529   576
   625   676   729   784   841   900   961  1024  1089  1156  1225  1296
  1369  1444  1521  1600  1681  1764  1849  1936  2025  2116  2209  2304
  2401  2500  2601  2704  2809  2916  3025  3136  3249  3364  3481  3600
  3721  3844  3969  4096  4225  4356  4489  4624  4761  4900  5041  5184
  5329  5476  5625  5776  5929  6084  6241  6400  6561  6724  6889  7056
  7225  7396  7569  7744  7921  8100  8281  8464  8649  8836  9025  9216
  9409  9604  9801 10000]

Elements divisible by 3: 
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
