In [3]:
import numpy as np

# Normalization Problem


#### > For this problem, we are tasked to create a function that can normalize a variable X that is a random 5 x 5 ndarray, then save the result. To achieve this, we first focus on making the function that utilizes the normalization formula:

In [22]:
#Create a 5x5 array with random values
X = np.random.random((5,5))

#Get mean of X
mean = X.mean()

#Get standard deviation of X 
std = X.std()

#Normalize X
Z = X-mean/std

#### > That covers the function itself, now we are able to print the result, as well as save the result. The combined code should be:

In [95]:
X = np.random.random((5,5))

mean = X.mean()

std = X.std()

Z = X-mean/std

#Equate Z to result
result = Z

#Print result; both X and Z arrays are printed for reference
print(" X array: \n", X)
print("\n Z array (X Normalized): \n", result)

#Save the result as 'X_normalized'
np.save('X_normalized', result)

 X array: 
 [[0.05630314 0.53701391 0.19462192 0.50539116 0.18725475]
 [0.26399482 0.10990701 0.37711777 0.81868357 0.74024503]
 [0.09967104 0.16465935 0.35796359 0.43523037 0.09519032]
 [0.0411547  0.76609523 0.77378704 0.86776541 0.6963337 ]
 [0.53251056 0.53876079 0.52803549 0.24078666 0.15875107]]

 Z array (X Normalized): 
 [[-1.4834318  -1.00272104 -1.34511303 -1.03434379 -1.35248019]
 [-1.27574012 -1.42982793 -1.16261718 -0.72105138 -0.79948991]
 [-1.44006391 -1.37507559 -1.18177136 -1.10450458 -1.44454463]
 [-1.49858025 -0.77363972 -0.76594791 -0.67196953 -0.84340124]
 [-1.00722439 -1.00097416 -1.01169945 -1.29894829 -1.38098388]]


#### > Code should result in such an output that displays two 5 x 5 arrays, X array and Z array (X Normalized), in an arranged manner. 

# Divisible by 3 Problem

#### > In this problem, a 10 x 10 ndarray of squares of the first 100 positive integers is to be created; then with this ndarray, a function is required to determine all the elements within it that are divisible by 3. Once the result is achieved, it should be saved. We can accomplish this by first creating the function:

In [46]:
#Create an array of positive integers from 1 to 100
positive_integers = np.arange(1,101)

#Create another array but of squares of positive integers from 1 to 100 by raising the first array to 2
A = positive_integers**2

#Reshape array A into 10 x 10 array
shape = A.reshape(10,10)

#Define a function so that elements divisible by 3 may be determined; true for divisible elements and false for otherwise
elements_divisible_by_3 = shape[shape%3==0] 

#### > Having made the function that divides and analyzes the array, printing and saving of result is now possible:


In [97]:
positive_integers = np.arange(1,101)

A = positive_integers**2

shape = A.reshape(10,10)

elements_divisible_by_3 = shape[shape%3==0] 

#Equate elements_divisible_by_3 to result
result = elements_divisible_by_3 

#Print result; squares of the first 100 positive integers before divided and analyzed is printed to compare to the found elements that are divisible by 3 
print("Squares of the first 100 positive integers: \n", A) 
print("\nElements divisible by 3: \n", result)

#Save the result as 'div_by_3.npy'
np.save('div_by_3.npy', result)

Squares of the first 100 positive integers: 
 [    1     4     9    16    25    36    49    64    81   100   121   144
   169   196   225   256   289   324   361   400   441   484   529   576
   625   676   729   784   841   900   961  1024  1089  1156  1225  1296
  1369  1444  1521  1600  1681  1764  1849  1936  2025  2116  2209  2304
  2401  2500  2601  2704  2809  2916  3025  3136  3249  3364  3481  3600
  3721  3844  3969  4096  4225  4356  4489  4624  4761  4900  5041  5184
  5329  5476  5625  5776  5929  6084  6241  6400  6561  6724  6889  7056
  7225  7396  7569  7744  7921  8100  8281  8464  8649  8836  9025  9216
  9409  9604  9801 10000]

Elements divisible by 3: 
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]


#### > The output from the code should first display the squares of the first 100 positive integers arranged in a 10 x 10 array. The proceeding output should then be elements divisible by 3 in a 10 x 10 array.